# Generated by Django 3.0.8 on 2020-09-02 07:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20200901_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Publication',
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-published_datetime'], 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
