# Generated by Django 3.0.8 on 2020-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20200901_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('picture', models.ImageField(upload_to='advisors/')),
                ('position', models.CharField(max_length=50)),
                ('linkedin', models.URLField()),
                ('bio', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
