# Generated by Django 3.0.8 on 2020-09-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='disp_priority',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
