# Generated by Django 3.0.8 on 2020-10-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_advisor_disp_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='clients/')),
                ('client_url', models.URLField()),
                ('disp_priority', models.IntegerField()),
            ],
            options={
                'ordering': ['disp_priority'],
            },
        ),
        migrations.AlterModelOptions(
            name='advisor',
            options={'ordering': ['disp_priority']},
        ),
    ]
