# Generated by Django 3.0.8 on 2020-10-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20201012_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
