# Generated by Django 3.0.8 on 2020-12-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20201121_2108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('chat', 'offset', 'by_admin')},
        ),
    ]
